services:
  api_1:
    build: ./api_1
    ports:
      - "8001:5000"
    volumes:
      - shared_storage:/data

  api_2:
    build: ./api_2
    ports:
      - "8002:5000"
    volumes:
      - shared_storage:/data

  api_3:
    build: ./api_3
    ports:
      - "8003:8003"
    volumes:
      - ./api_3/db.json:/app/db.json
    restart: always

  ui:
    build: ./frontend
    ports:
      - "80:80"

volumes:
  shared_storage:
